# Generated by Django 5.0 on 2024-01-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0002_news_picture_news_updated_at_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
