# Generated by Django 5.0 on 2024-01-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0005_alter_news_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/news/%Y/%m.%d/%H:%M'),
        ),
    ]
