# Generated by Django 5.0 on 2024-01-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0007_alter_news_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='updated_at',
        ),
    ]
