# Generated by Django 5.0 on 2024-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0009_alter_news_created_at_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
    ]
