# Generated by Django 5.0 on 2024-01-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0010_alter_news_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug_url',
            field=models.SlugField(default='default_slug', verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
