# Generated by Django 5.0 on 2024-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0011_news_slug_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug_url',
            field=models.SlugField(unique=True, verbose_name='Ссылка'),
        ),
    ]
