# Generated by Django 5.0 on 2024-02-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0013_rubric_news_rubrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
