# Generated by Django 5.0 on 2024-02-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0015_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
    ]
