# Generated by Django 5.0 on 2024-02-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0026_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Свойство', 'verbose_name_plural': 'Свойства'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
    ]
