# Generated by Django 5.0 on 2024-02-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0031_workcomponent_unique_work_component'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workcomponent',
            name='unique_work_component',
        ),
        migrations.AddConstraint(
            model_name='workcomponent',
            constraint=models.UniqueConstraint(fields=('work', 'component'), name='unique_work_component'),
        ),
    ]
