# Generated by Django 5.0 on 2024-02-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0035_workcomponent_unique_work_component'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Разработка', 'verbose_name_plural': 'Разработки'},
        ),
        migrations.AlterField(
            model_name='workcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.component', verbose_name='Свойство'),
        ),
        migrations.AlterField(
            model_name='workcomponent',
            name='filling',
            field=models.TextField(blank=True, null=True, verbose_name='Заполнение'),
        ),
        migrations.AlterField(
            model_name='workcomponent',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.work', verbose_name='Разработка'),
        ),
    ]
