# Generated by Django 5.0 on 2024-02-27 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0037_vacancy_vcomponent_wcomponent_vacancycomponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название свойства')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.AlterField(
            model_name='vacancycomponent',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.work', verbose_name='Разработка'),
        ),
        migrations.AlterField(
            model_name='vcomponent',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название свойства'),
        ),
        migrations.AlterField(
            model_name='workcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.component', verbose_name='Свойство'),
        ),
        migrations.DeleteModel(
            name='WComponent',
        ),
    ]
