# Generated by Django 5.0 on 2024-02-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0040_alter_vacancycomponent_vacancy'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vacancycomponent',
            name='unique_vacancy_component',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='components',
            field=models.ManyToManyField(through='e5_app.VacancyComponent', to='e5_app.vcomponent'),
        ),
    ]
