# Generated by Django 5.0 on 2024-02-29 11:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0043_remove_workcomponent_unique_work_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
