# Generated by Django 5.0 on 2024-03-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0044_vacancy_content'),
        ('e5_app', '0044_vacancy_slug_url'),
    ]

    operations = [
    ]
