# Generated by Django 5.0 on 2024-03-07 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0050_alter_event_options_alter_visitor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='choice',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.eventtype', verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.eventschedule'),
        ),
    ]
