# Generated by Django 5.0 on 2024-03-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0052_mailing_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
