# Generated by Django 5.0 on 2024-03-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0055_alter_mailing_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='name',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
