# Generated by Django 5.0 on 2024-03-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0056_remove_mailing_name_alter_mailing_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(unique=True, verbose_name='Название пути')),
                ('content', models.TextField(verbose_name='Контент для поиска')),
            ],
            options={
                'verbose_name': 'Страница HTML',
                'verbose_name_plural': 'Страницы HTML',
            },
        ),
    ]
