# Generated by Django 5.0 on 2024-03-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0058_htmlpage_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.CharField(choices=[('a', 'Описание и фото'), ('d', 'Описание'), ('p', 'Фото')], default='a', verbose_name='Отображение на странице новости'),
        ),
    ]
