# Generated by Django 5.0 on 2024-03-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0059_news_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='show',
            field=models.CharField(choices=[('a', 'Описание и фото'), ('d', 'Описание'), ('p', 'Фото')], default='a', verbose_name='Отображать странице новости'),
        ),
    ]
