# Generated by Django 5.0 on 2024-03-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0060_alter_news_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rubrics',
            field=models.ManyToManyField(to='e5_app.rubric', verbose_name='Рубрики'),
        ),
    ]
