# Generated by Django 5.0 on 2024-03-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0063_alter_news_description_alter_news_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
