# Generated by Django 5.0 on 2024-03-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0066_alter_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
