# Generated by Django 5.0 on 2024-04-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0067_alter_employee_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название'),
        ),
    ]
