# Generated by Django 5.0 on 2024-04-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0070_alter_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['pk'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
    ]
