services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000 && celery -A e5_app worker -l info"
    volumes:
      - type: bind
        source: .
        target: /usr/src/e5_site/
    ports:
      - 0.0.0.0:8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A e5_app worker -l info
    volumes:
      - type: bind
        source: .
        target: /usr/src/e5_site/
    depends_on:
      - web
  db:
    image: postgres:14.11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=e5_db_docker
  redis:
    image: redis:7

volumes:
  postgres_data:
