services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - type: bind
        source: .
        target: /usr/src/e5_site
    ports:
      - 8000:8000
    env_file:
      - ./.env