# Generated by Django 5.0 on 2024-02-07 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0016_alter_news_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
