# Generated by Django 5.0 on 2024-02-26 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0018_alter_news_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/employee/', verbose_name='Фото')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('description', models.TextField(max_length=500, verbose_name='Информация')),
                ('email_first', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Первая почта')),
                ('email_second', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Вторая почта')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 26, 10, 11, 56, 281412), verbose_name='Дата создания'),
        ),
    ]
