# Generated by Django 5.0 on 2024-02-26 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0019_employee_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 26, 10, 14, 17, 167555), verbose_name='Дата создания'),
        ),
    ]
