# Generated by Django 5.0 on 2024-02-26 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0021_alter_employee_options_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 26, 11, 5, 53, 32886), verbose_name='Дата создания'),
        ),
    ]
