# Generated by Django 5.0 on 2024-02-26 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0023_component_work_alter_news_created_at_workcomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 26, 14, 12, 50, 50315), verbose_name='Дата создания'),
        ),
    ]
