# Generated by Django 5.0 on 2024-02-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0029_remove_workcomponent_unique_work_component_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workcomponent',
            name='unique_work_component',
        ),
    ]
