# Generated by Django 5.0 on 2024-02-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0034_remove_workcomponent_unique_work_component'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workcomponent',
            constraint=models.UniqueConstraint(fields=('work', 'component'), name='unique_work_component'),
        ),
    ]
