# Generated by Django 5.0 on 2024-02-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0036_alter_work_options_alter_workcomponent_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/works/', verbose_name='Фото')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заработная плата')),
                ('experience', models.CharField(blank=True, max_length=100, null=True, verbose_name='Опыт работы')),
                ('schedule', models.CharField(blank=True, max_length=100, null=True, verbose_name='График труда')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filling', models.TextField(blank=True, null=True, verbose_name='Заполнение')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.work', verbose_name='Вакансия')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.vcomponent', verbose_name='Свойство')),
            ],
        ),
        migrations.AlterField(
            model_name='workcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.wcomponent', verbose_name='Свойство'),
        ),
        migrations.AddConstraint(
            model_name='vacancycomponent',
            constraint=models.UniqueConstraint(fields=('vacancy', 'component'), name='unique_vacancy_component'),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
    ]
