# Generated by Django 5.0 on 2024-02-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0038_component_alter_vacancycomponent_vacancy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='vcomponent',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='workcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.wcomponent', verbose_name='Свойство'),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
    ]
