# Generated by Django 5.0 on 2024-02-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0039_wcomponent_alter_vcomponent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancycomponent',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.vacancy', verbose_name='Вакансия'),
        ),
    ]
