# Generated by Django 5.0 on 2024-02-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0041_remove_vacancycomponent_unique_vacancy_component_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcomponent',
            options={'verbose_name': 'Свойство вакансий', 'verbose_name_plural': 'Свойства вакансий'},
        ),
        migrations.AlterModelOptions(
            name='wcomponent',
            options={'verbose_name': 'Свойство разработок', 'verbose_name_plural': 'Свойства разработок'},
        ),
    ]
