# Generated by Django 5.0 on 2024-02-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0042_alter_vcomponent_options_alter_wcomponent_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workcomponent',
            name='unique_work_component',
        ),
    ]
