# Generated by Django 5.0 on 2024-03-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0043_remove_workcomponent_unique_work_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='slug_url',
            field=models.SlugField(default='hello', unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
