# Generated by Django 5.0 on 2024-03-06 11:09

import colorfield.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0048_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, unique=True, verbose_name='Цвет отображения')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('info', models.TextField(blank=True, max_length=500, null=True, verbose_name='Дополнительно')),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None, verbose_name='Время[ - место]')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.eventtype')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('stand', models.CharField(choices=[('ab', 'Абитуриент'), ('11', '11 класс'), ('10', '10 класс'), ('dr', 'Другое')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
