# Generated by Django 5.0 on 2024-03-07 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0049_eventtype_event_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Посетитель', 'verbose_name_plural': 'Посетители'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Время начала')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='Время конца')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место проведения')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e5_app.event')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
