# Generated by Django 5.0 on 2024-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0053_alter_mailing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='phone',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
