# Generated by Django 5.0 on 2024-03-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0054_remove_mailing_phone_alter_mailing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
