# Generated by Django 5.0 on 2024-03-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0057_htmlpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlpage',
            name='verbose',
            field=models.CharField(default='Привет', verbose_name='Название страницы'),
            preserve_default=False,
        ),
    ]
