# Generated by Django 5.0 on 2024-03-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0062_alter_news_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='show',
            field=models.CharField(choices=[('a', 'Описание и картинка'), ('d', 'Описание'), ('p', 'Картинка'), ('e', 'Ничего')], default='a', verbose_name='Отображать странице новости'),
        ),
    ]
