# Generated by Django 5.0 on 2024-04-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0068_alter_partner_options_alter_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, verbose_name='Дата создания'),
        ),
    ]
