# Generated by Django 5.0 on 2024-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e5_app', '0071_alter_vacancy_options_alter_rubric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='Дата создания'),
        ),
    ]
